<?php
$categoryImageSize = $this->getCategoryImageSize();
$optionsHelper = $this->helper('TemplateMonster\ThemeOptions\Helper\Data');
?>
.category-image {margin: 0 auto; max-width: <?php echo $categoryImageSize['max-width'] ?>px;max-height: <?php echo $categoryImageSize['max-height'] ?>px;}
.wrapper ul, .wrapper ol {font-size: 0;margin:0 -5px;}
.wrapper li {display: inline-block;width: 33.33%;margin-bottom: 25px;vertical-align: top;text-align: center;box-sizing:border-box;padding:0 5px;}
.wrapper li .price-box {margin:10px 0 5px}
.sidebar-main{width:23%;padding-right:2%;display:inline-block;vertical-align:top}
.filter-subtitle{display:none;border:1px solid #E0E0E0;border-radius:7px;font-weight:400;padding:13px 30px;text-transform:capitalize;position:relative;font-size:15px}
.filter-subtitle:after{content:"\f107";font-family:'FontAwesome';display:inline-block;vertical-align:middle;position:absolute;right:30px;top:12px;font-size:16px}
.filter .filter-title{padding: 0 10px 15px 10px;border-bottom: 1px solid #ccc}
.filter-actions{margin:0 0 15px}
.filter-content label{user-select:none}
.filter-options input[type="checkbox"]{display:none}
.filter-options > li > label{padding:14px 10px 14px 30px;display:block;border-bottom:1px solid #ccc;position:relative;text-transform:uppercase;font-weight:700;font-family:Poppins,sans-serif}
.filter-options input[type="checkbox"]:checked + label + .items{display:block}
.filter-options .items,.filter-options .swatch-attribute{border-bottom:1px solid #ccc;padding:0 10px 10px 30px;margin:0;display:none}
.filter-options .swatch-attribute{padding-top:10px}
.filter-options .swatch-attribute li{display:inline-block;margin: 0 10px 5px 0;padding:0;line-height:normal}
.filter-options .items .item{margin: 10px 0;font-size:15px}
.filter-options table.swatch-option{display:inline-block;width:30px;height:20px;margin:0;border: 1px solid #dadada;border-collapse:collapse}
.filter-options table.swatch-option td{width:30px;height:18px}
.filter-options .item a,.filter-options .item a:hover,.filter-options .swatch-option-link-layered,.filter-options .swatch-option-link-layered:hover{color:#494949}
#filter-items:checked + .filter-subtitle:after{top:12px}
.filter-options > li > label:after{content:"\f107";display:inline-block;vertical-align:middle;position:absolute;right:31px;top:15px;font-size:16px;font-family:"FontAwesome"}
.filter-options input[type="checkbox"]:checked + label:after{content:"\f106"}
.filter-options input[type="checkbox"]:checked ~ .items,.sidebar-main .filter-options input[type="checkbox"]:checked ~ .swatch-attribute{display:block}
.filter-options .item .count {color: #a0a0a0;}
.filter-options .item .count:before {content: "(";}
.filter-options .item .count:after {content: ")";}
.filter-options .item .count span{display: none}
.filter-options .items {padding-top:10px;}
.filter-content .block-subtitle{display:none}
.filter-content #filter-items{display:none}
.filter-content #filter-items:checked ~ #narrow-by-list{display:block}
.filter-content .filter-current .block-subtitle{display:block}
.filter-current li{margin:3px 0 3px 10px;position:relative;padding-right:25px}
.filter-current li:before,.filter-current li:after{content:"";display:block;clear:both}
.filter-current .filter-label:after{content:":"}
.filter-current .item .remove{margin-left:6px;display:inline-block;width:20px;height:20px;border:1px solid #ededed;text-align:center;font:0/0 a;text-shadow:none;color:transparent;position:absolute;background:#fff;right:0;top:0}
.filter-current .item .remove:before{content:"";display:inline-block;width:12px;height:13px;position:absolute;border-top:1px solid;transform:rotate(45deg);transform-origin:center;top:50%;left:50%;margin-top:-2px;margin-left:-11px}
.filter-current .item .remove:after{content:"";display:inline-block;width:12px;height:12px;position:absolute;border-top:1px solid;transform:rotate(-47deg);transform-origin:center;top:50%;left:50%;margin-top:-2px;margin-left:-2px}
.limiter span,.limiter label,.limiter .control{display:inline-block;vertical-align:middle}
.limiter .limiter-options{margin:0 15px}
.limiter .limiter-options a{background-color:#f0f0f0;border-radius:7px;display:inline-block;color:#333;padding:3px 8px;margin:0 1px}
.column.main{width:75%;display:inline-block;vertical-align:top}
.sorter a{display:inline-block;margin-right:5px;line-height:18px;border:2px solid #fff;padding:8px 6px;background:transparent;font-size:14px;border-radius:7px;color:#fff;}
.sorter a.sorter-active{background:#fff;}
.sorter a:hover{text-decoration:none}
.sorter-label{font-size:13px;display:inline-block;margin-right:7px; color: #fff;}
.sort-by-switcher{display:inline-block;width:25px;overflow:hidden;text-indent:-999px;vertical-align:middle;text-align:center;vertical-align:top}
.sort-by-switcher:before{font-family:FontAwesome;font-size:14px;display:block;text-indent:0}
.sort-by-switcher.sort-desc:before{content:"\f107"}
.sort-by-switcher.sort-asc:before{content:"\f106"}
.sort-by-switcher span{display: none;}
.pages {margin-bottom: 25px; text-align: center; display:none}
.pages .items {
    font-size: 0;
    letter-spacing: -1px;
    line-height: 0;
    white-space: nowrap;
    list-style: none none;
   	display: flex;
   	justify-content: center;
    font-weight: 400;
    text-align: center;
    position: relative;
    z-index: 1;
}
.pages .item {
    font-size: 16px;
    letter-spacing: normal;
    line-height: 24px;
    margin: 0 15px;
    display: inline-block;
}
.pages .action {
    color: #E0E0E0;
    padding: 0 8px;
    display: inline-block;
    text-decoration: none;
    font-size: 20px;
}
.pages .action.next:before,
.pages .action.previous:before{
    font-family:FontAwesome;
    font-size: 20px;
    display: inline-block;
    position: relative;
}
.pages .action.next:before{content: "\f105"; }
.pages .action.previous:before{content: "\f104"; }
.pages .action>span,.pages > .label,.pages .item .label,.special-price .price-label,.old-price .price-label {display: none;}
.product-item-details {font-size: 15px;}
.special-price, .old-price {display: block;}
.old-price .price {text-decoration: line-through; color: #b3b3b3;}
.actions-primary>a,
.actions-primary>button {
    display: inline-block;
    background: transparent;
    line-height: 30px;
    padding: 7px 15px;
    margin: 8px 0;
    min-width: 120px;
    border-radius: 40px;
    border: 2px solid;
}
.actions-primary>a:hover{
    color: #fff;
    text-decoration: none;
}
.stock.unavailable {color:red;}
.toolbar-amount { color: #BDBDBD; }
.bottom-toolbar {margin: 15px 0;padding:0;font-size: 0;}
.bottom-toolbar > .toolbar > * {display:none}
.bottom-toolbar > .toolbar > .pages {display:block; padding:10px 0}
.bottom-toolbar > .toolbar > .pages .item{padding:3px 8px;border:1px solid #fff;border-radius:3px;color:#fff; width:32px;height:32px;margin:0 4px;line-height:32px;}
.bottom-toolbar > .toolbar > .pages .item a{color:#fff}
.bottom-toolbar > .toolbar > .pages .item.current{padding:3px 8px;background:#fff;}
@media (max-width: 780px) {
.sidebar-main{width:100%;display:block;box-sizing:border-box;padding:0}
.sidebar-main .filter-options{margin:0;display:none}
.column.main{width:100%;display:block;box-sizing:border-box}
.filter .filter-title{display:none}
.sidebar-main .filter-subtitle{display:block}
.toolbar-sorter{margin:15px -1000px;padding:10px 1000px;font-size:0}
.bottom-toolbar {margin: 15px -1000px;padding: 0 1000px;}
}
@media (max-width: 490px) {
.wrapper li {width: 50%}
.pages .items {
    padding: 0 54px 0;
}
}
@media (max-width: 340px) {
.wrapper li {width: 100%}
}
.product-item-info .product-item-photo {background:#f2f2f2;margin-bottom:15px;display:block;}
.product-item-info .product-item-link {color:#202020;font-size:15px;line-height:20px;margin-bottom:10px;font-weight:100;padding: 0 5px;overflow: hidden; white-space: nowrap;text-overflow: ellipsis; display:inline-block; }
.price-slider {padding:15px 0 5px 30px;}
.slider-fields > div {display:inline-block; margin-right:5px;}

.toolbar-sorter,
.bottom-toolbar,
.actions-primary>a:hover {
<?php if ($optionsHelper->getPrimaryColor()): ?>
    background-color: <?php echo $optionsHelper->getPrimaryColor(); ?>;
<?php endif; ?>
}

.actions-primary>a,
.actions-primary>button,
.sorter a.sorter-active,
.bottom-toolbar > .toolbar > .pages .item.current,
span[data-price-type="finalPrice"] {
<?php if ($optionsHelper->getPrimaryColor()): ?>
    color: <?php echo $optionsHelper->getPrimaryColor(); ?>;
<?php endif; ?>
}

.filter-current .item .remove:before,
.filter-current .item .remove:after,
.actions-primary>a,
.actions-primary>button {
<?php if ($optionsHelper->getPrimaryColor()): ?>
    border-color: <?php echo $optionsHelper->getPrimaryColor(); ?>;
<?php endif; ?>
}