<?php $optionsHelper = $this->helper('TemplateMonster\ThemeOptions\Helper\Data'); ?>
@font-face {
    font-family:"Material Icons";
    src:  url(<?php echo $this->getAmpSkinUrl('Zemez_Amp::fonts/material-icons/MaterialIcons-Regular.eot')?>);
    src: url(<?php echo $this->getAmpSkinUrl('Zemez_Amp::fonts/material-icons/MaterialIcons-Regular.ttf')?>) format('truetype'),
    url(<?php echo $this->getAmpSkinUrl('Zemez_Amp::fonts/material-icons/MaterialIcons-Regular.woff')?>) format('woff'),
    url(<?php echo $this->getAmpSkinUrl('Zemez_Amp::fonts/material-icons/MaterialIcons-Regular.svg') ?>) format('svg');
    font-weight: normal;
    font-style: normal;
}

body{margin:0;padding:0;font-family:Poppins,Arial,sans-serif;left:0;top:0;}
body,button,input,select,table,textarea{color:#888;font-size:14px;line-height:1.5}
a{text-decoration:none}
a{
<?php if ($optionsHelper->getPrimaryColor()): ?>
    color: <?php echo $optionsHelper->getPrimaryColor(); ?>;
<?php endif; ?>
}

a:hover{color:#000000;text-decoration:underline}
a:focus{outline:none;color:#143d52}
ol,ul{list-style:none;margin:0;padding:0}
.desktop{display:block}
.header.content:after,
.clearfix:before,
.clearfix:after,
.column.main:after {content:"";display:block;clear:both}

h1,.h1,h2,.h2,h3,.h3,h4,.h4,h5,.h5,h6,.h6{margin:0;font-family:Poppins,sans-serif;font-style:normal;line-height:1.2;text-transform:uppercase;font-weight:400;color:#636363;margin-bottom:0.5em}
h1,.h1{font-size:21px}
h2,.h2{font-size:18px}
h3,.h3{font-size:16px}
h4,.h4{font-size:14px}
h5,.h5{font-size:13px}
h6,.h6{font-size:12px}
.icon,.icon:before{font-family: 'FontAwesome';display:inline-block;vertical-align:top;width:30px;height:30px;line-height:30px;text-align:center;font-size:24px}
.page-wrapper{position:relative;max-width:1260px;margin:0 auto;padding:10px 10px}
button{background:transparent;display:inline-block;padding:7px 15px;border:0;color:#00A486;font-size:15px;line-height:normal;text-transform:uppercase;margin:10px 0 0 0;border: 1px solid #F2F2F2;}
.page-title {margin-top: 15px}

.message{font-size:.8rem;margin:0 0 10px;padding:12px 20px 12px 25px;display:block;padding-left:45px;position:relative}
.message.info{background:#fdf0d5;color:#6f4400}
.message.info a{color:#1979c3}
.message.info a:hover{color:#006bb4}
.message.info a:active{color:#006bb4}
.message.error{background:#fae5e5;color:#e02b27}
.message.error a{color:#1979c3}
.message.error a:hover{color:#006bb4}
.message.error a:active{color:#006bb4}
.message.warning{background:#fdf0d5;color:#6f4400}
.message.warning a{color:#1979c3}
.message.warning a:hover{color:#006bb4}
.message.warning a:active{color:#006bb4}
.message.notice{background:#fdf0d5;color:#6f4400}
.message.notice a{color:#1979c3}
.message.notice a:hover{color:#006bb4}
.message.notice a:active{color:#006bb4}
.message.success{background:#e5efe5;color:#006400}
.message.success a{color:#1979c3}
.message.success a:hover{color:#006bb4}
.message.success a:active{color:#006bb4}

.actions-primary>a,
.actions-primary>button {
display: inline-block;
background: transparent;
line-height: 30px;
padding: 0 15px;
color: #00A486;
margin: 8px 0;
min-width: 120px;
border-radius: 7px;
}

.header.content{padding:7px 15px;position:relative;border-bottom:1px solid #ccc}
.right-top-btn {float: right; margin-top: 8px; }

.mobile-menu{display:inline-block;cursor:pointer;left:10px;position:absolute;top:16px;z-index:14;}
.mobile-menu:before,
.search-icon:before,
.account:before,
.cart:before {color: #BDBDBD; content: "\f07a";}
.icon.cart{width:auto;}

.mobile-menu:before {content: "\f0c9"; color:#4F4F4F }
.account:before {content: "\f2c0";}
.search-icon:before {content: "\f002"; }
.cart .count{webkit-border-radius:2px;-moz-border-radius:2px;-ms-border-radius:2px;-o-border-radius:2px;border-radius:2px;display:block;position:relative;z-index:5;min-width:18px;height:24px;background:#ff5501;color:#FFFFFF;font-size:11px;line-height:24px;text-align:center;font-family:"Helvetica Neue",Verdana,Arial,sans-serif;vertical-align: top; margin-top: 3px;float: right;}

.mobile-menu:hover:before,
.account:hover:before,
.search-icon:hover:before,
.cart:hover:before {color:#BDBDBD}

.amp-logo-container{width:30%;float:left;margin:0 0 0 35px;max-width:150px;min-width:100px;position:relative;z-index:5;line-height:45px;min-height:45px}
.amp-logo-container .amp-logo{display:inline-block;width:100%;vertical-align:middle}
.amp-logo-container amp-img {vertical-align: middle}

.amp-navigation {background:#fff;border-bottom: 1px solid #ccc;}
.amp-navigation li {position: relative}

.amp-navigation ul li a,
.amp-navigation ul li a span,
.amp-navigation ul li label,
.amp-navigation ul li label span {display: block; color: #4f4f4f; padding: 7px 0}
.amp-navigation ul li.level0>label span {color: #4f4f4f;}
.amp-navigation ul li a span,
.amp-navigation ul li label span {padding: 0}
.amp-navigation li.active {color: #00a486;}
.amp-navigation ul>li {font-size: 14px; padding: 0 0px 0 10px; }
.amp-navigation ul>li.level0{border-top:1px solid #d1d1d1;font-weight:700;text-transform:uppercase}
.amp-navigation ul>li.level0 li.level0 {border-top: 0}

.amp-navigation ul ul {text-transform: none}
.amp-navigation ul>li.level0 ul li {font-weight: 400}

.amp-navigation li input[type=checkbox] + label {position: relative}
.amp-navigation li input[type=checkbox] + label:after{content:"\f106";width:16px;height:16px;display:block;position:absolute;z-index:14;right:15px;top:10px;line-height:16px;font-family:"FontAwesome";font-size:16px;color:#000}
.amp-navigation li input[type=checkbox]:checked + label:after{content: "\f107"}

.breadcrumbs{display: none;}
.breadcrumbs li{float:left;font-size:12px;font-family:Poppins,Arial,sans-serif;text-transform:uppercase; margin-right: 10px}
.breadcrumbs li::after {content: "/";margin: 10px}
.breadcrumbs li:last-child::after {display: none}
.breadcrumbs a{float:left;color:#00A486}
.breadcrumbs a:hover{color:#00A486}
.breadcrumbs strong{color:#262626;font-weight:normal}
.breadcrumbs span{float:left;padding:0 7px}

.page-wrapper {max-width: 1280px; margin: 0 auto}
.amp-page-main  {padding: 10px}

.main-container{padding:30px;position:relative}
.main-container:before,.main-container:after{content:"";display:block;clear:both}

.amp-iframe-placeholder{background: #f4f4f4;font-weight:700;text-align: center}
.amp-iframe-placeholder span{position: relative;top: 60%}

.sharing-conttainer{padding-top:20px}
.sharing-conttainer .title{font-weight:700}
.sharing-conttainer .buttons{display:flex}
.sharing-conttainer .buttons amp-social-share{margin:2px}

.footer-container{padding:0 30px}
.footer{width:100%;border-top:1px solid #cccccc;padding-top:15px;text-align:center;font-size:12px}
.footer address{border-top:1px solid #cccccc;text-align:center;width:100%;font-size:11px;margin-top:15px;padding:20px 0;font-style:normal}
.footer li{display:inline-block;padding:0 10px}

.amp-navigation,
.amp-navigation li ul {display: none}
.amp-navigation li ul {padding-bottom:10px;}
#mitem-amp-navigation,.amp-navigation li input[type=checkbox]{position:absolute;top:-9999px;left:-9999px}
#mitem-amp-navigation:checked + .amp-navigation,
.amp-navigation li input[type=checkbox]:checked + label + ul {display: block}
.amp-navigation li input[type=checkbox]:checked + label {text-transform: none; font-weight: 100;}

.minisearch .field.search,.minisearch .actions {display:inline-block}
.minisearch button {margin:0}
.minisearch #search{height:27px;padding:0 5px;line-height:25px;border-radius:0;border:1px solid #b0b0b0;box-shadow:none}

.amp-iframe-placeholder{background: #f4f4f4;font-weight:700;text-align: center;}
.amp-iframe-placeholder span{position: relative;top: 60%;}

@media (max-width:770px){
.breadcrumbs,
.desktop{display:none}
}

@media (max-width:640px){
.main-container{padding:10px 15px}
.footer-container{padding:0 15px}
}

@media (max-width:360px){
.footer>ul {font-size: 0}
.footer ul li {font-size: 12px; width: 50%; box-sizing: border-box; margin: 3px 0}
}

@media (min-width:770px){
.mobile-menu {display: none}
.amp-logo-container {margin-left: 2px}
.header.content, .amp-navigation {display: block; border-bottom: 0}
.amp-navigation ul>li.level0{margin:0 10px 0 0;display:inline-block;position:relative;vertical-align:top;text-transform:none;border-top:0;color:#4f4f4f;}
.amp-navigation ul>li.level0 label span {color:#4f4f4f;}
.amp-navigation>ul>li.level0>label:after,
.amp-navigation li input[type=checkbox] {display: none}
.amp-navigation ul li a,.amp-navigation ul li label {padding: 10px 2px}
.amp-navigation li input[type=checkbox]:checked + label + ul.level0{display:block;position:absolute;z-index:50;background:#fff;border:1px solid #ccc;box-shadow:0 5px 5px rgba(0,0,0,0.19);font-weight:400;min-width:230px}
.amp-navigation li input[type=checkbox] + label:after {top: 13px; right: 15px}
.amp-navigation li input[type=checkbox]:checked + label + ul ul{position:static;box-shadow:none;border:0}
}

.right-top-btn .icon:before { font-family: 'FontAwesome'; font-size:24px; line-height: 28px;}
