<form id="order-success" action="<?php echo $this->getUrl('orderdetails/index/saveCake'); ?>" method="post" enctype= "multipart/form-data">
    <!-- ============================== Fieldset 1 ============================== -->
    <input class="inp-text" name="customer_id"  type="hidden" size="30" value="<?php echo Mage::getSingleton('customer/session')->getCustomer()->getId(); ?>" />
    <input class="inp-text" name="name"  type="hidden" size="30" value="Customized Cake" />
    <input class="inp-text" name="sku"  type="hidden" size="30" value="<?php echo time(); ?>" />
    <div class="form-box wide">
        <h6 class="legend">Please provide following information regarding your order.</h6>
        <br>        <ul class="form-list">
            <li class="fields">
                <div class="customer-name-middlename">
                    <div class="field name-email">
                        <label for="cake type" class="required"><em>*</em>Cake Type</label>
                        <div class="input-box">
                            <select id="cake_type" name="cake_type" class="required-entry required-entry select ">
                                <option value="42">Egg</option>
                                <option value="41">Eggless</option>
                            </select>
                        </div>
                    </div>
                    <div class="field name-delivey_date">
                        <label for="delivey_date" class="required"><em>*</em>Cake image</label>
                        <div class="input-box">
                            <input type="file" id="delivey_date" name="image"
                                   title="Delivery Date" maxlength="255" class="input-text required-entry">
                        </div>
                    </div>
                </div>
            </li>
            <!--            <li>
                            <label for="delivery_time" class="required"><em>*</em>Delivery Time</label>
                            <div class="input-box">
                                <input type="text" name="delivery_time" id="delivery_time" value="" title="Delivery Time" 
                                       class="input-text required-entry">
                            </div>
                        </li>-->
        </ul>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="special_request" class="required"><em>*</em>Weight</label>
                    <div class="input-box">
                        <input type="text" name="special_request" id="special_request" title="Password"
                               class="input-text">
                    </div>
                </div>
                <div class="field">
                    <label for="other_contact_number" class="required"><em>*</em>Alternate Contact Number</label>
                    <div class="input-box">
                        <input type="other_contact_number" name="other_contact_number"
                               title="Alternate Contact Number" id="other_contact_number" class="input-text">
                    </div>
                </div>
            </li>
        </ul>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="Message" class="required"><em>*</em>Message On Cake</label>
                    <div class="input-box">
                        <input type="textarea" name="message" id="Message" title="Message" class="input-text">
                    </div>
                </div>
            </li>
        </ul>
        <h6>
            This request will be submitted with a security cost of 500. After confirmation 
            we will inform you the exact cost for the cake. And then rest amount will be paid at the time of delivery. And if you are not satisfied with the costing, 
            instant refund will be provided.
        </h6>
        <div class="buttons-set">
            <p class="required">* Required Fields</p>
            <button type="submit" title="Submit" class="button"><span><span>Submit</span></span></button>
        </div>

    </div>
</form>
<script>
    var dataForm = new VarienForm('order-success', true);
</script>