<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license/regular
 */
/**
 * head.phtml
 */
?>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title><?php echo $this->getTitle() ?></title>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<base href="<?php echo $this->getBaseUrl(); ?>"/>
<meta name="Author" content="<?php echo $this->getBaseUrl(); ?>"/>
<meta name="page-topic" content="Mid Night Gifts Delivery in Jaipur"/>
<meta name="copyright" content="The Mid Night Gifts 2017"/>
<meta name="rating" content="safe for kids"/>
<meta name="googlebot" content=" index, follow "/>
<meta name="yahooSeeker" content=" index, follow "/>
<meta name="msnbot" content=" index, follow "/>
<meta name="allow-search" content="yes"/>
<meta name="revisit-after" content="daily"/>
<meta name="distribution" content="global"/>
<meta name="Rating" content="General"/>
<meta name="expires" content="never"/>
<meta name="language" content="english"/>
<meta name="summary" content="<?php echo htmlspecialchars($this->getDescription()) ?>"/>
<meta about="<?php echo $this->getBaseUrl(); ?>" property="sioc:num_replies" content="0" datatype="xsd:integer"/>
<meta name="page-topic" content="The Mid Night Gifts delivery in Jaipur Rajasthan"/>
<meta http-equiv="Bulletin-Text" content="The Mid Night Gifts Delivery in Jaipur Rajasthan"/>
<meta name="fragment" content="The Mid Night Gifts Delivery in Jaipur Rajasthan"/>
<meta name="Abstract" content="The Mid Night Gifts Delivery in Jaipur Rajasthan"/>
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />

<?php echo Mage::helper('itactica_intenso')->getGoogleFontsScript() ?>
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>